# Site settings
author: Paul Narducci
title: A Look at Use of Force in Indianapolis 
header-img: img/home-bg.png
email: paulvnar@gmail.com
copyright_name: Paul Narducci
description: > # this means to ignore newlines until "baseurl:"
  Applying machine learning to use of force by the IMPD
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PNarducci

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
